version: "3"

services:
  ah-always-delivery-mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - allways-deliver-net


  ah-always-delivery-mongo:
    build: ./src/main/docker
    image: ah-always-delivery-mongo
    ports:
      - "8081:8081"
    depends_on:
      - ah-always-delivery-mongo
    networks:
      - allways-deliver-net

networks:
  allways-deliver-net:
    driver: bridge

