version: "3"

services:
  ah-always-delivery-mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - always-deliver-net


  always-deliver:
    build: ./src/main/docker-local
    image: always-deliver
    ports:
      - "8081:8081"
    depends_on:
      - ah-always-delivery-mongo
    networks:
      - always-deliver-net

networks:
  always-deliver-net:
    driver: bridge

