version: "3"

services:
  mongo-delivery:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - allways-deliver-net
    hostname: mongo.delivery

  always-deliver:
    build: ./src/main/docker
    image: always-deliver
    ports:
      - 8081:8081
    depends_on:
      - mongo-delivery
    networks:
      - allways-deliver-net

networks:
  allways-deliver-net:
    driver: bridge

