apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "ah-allways-deliver-rest"
  labels:
    run: ah-allways-deliver-rest
    name: ah-allways-deliver-rest
    tier: frontend
    role: web-application
    team-channel: team-ronin-notifications
    support-level: "8x5"
  annotations:
    devops.ah.it/support-level: "8x5"
    devops.ah.it/git-repo: "##GIT_REPO##"
    devops.ah.it/git-branch: "##GIT_BRANCH##"
    devops.ah.it/git-commit: "##COMMIT_HASH##"
spec:
  selector:
    matchLabels:
      run: ah-allways-deliver-rest
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: ah-allways-deliver-rest
        name: ah-allways-deliver-rest
        team-channel: team-ronin-notifications
        support-level: "8x5"
      annotations:
        devops.ah.it/support-level: "8x5"
        devops.ah.it/git-repo: "##GIT_REPO##"
        devops.ah.it/git-branch: "##GIT_BRANCH##"
        devops.ah.it/git-commit: "##COMMIT_HASH##"
    spec:
      imagePullSecrets:
        - name: docker-registry
        - name: docker-registry-secure
      containers:
      - command: ["mvn"]
        args: ["spring-boot:run", "-f" ,"~/always-deliver"]
        image: docker-registry-dev.ecom.ahold.nl:443/ah-allways-deliver-rest:latest
        resources:
          limits:
            memory: 786Mi
            cpu: 1
          requests:
            memory: 512Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /health-check/ping
            port: 8081
          initialDelaySeconds: 45
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health-check/ping
            port: 8081
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 1
        name: ah-allways-deliver-rest

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: ah-allways-deliver-rest
  name: ah-allways-deliver-rest
spec:
  ports:
  - name: ah-allways-deliver-rest
    targetPort: 8081
    port: 80
    protocol: TCP
  selector:
    run: ah-allways-deliver-rest
